### ISSUE TITLE
breaking on keywords as method names on continuation lines

### ISSUE THREAD

**Issue by smurp** [decaffeinate/coffee-lex#245]
decaffeinate is crashing on my CoffeeScript input:

```coffee
class Whatever
   no_problem: ->
     @jqueryElem.
       whatever().
       non_coffeescript_keyword('a', 2)
   explodes: ->
     @jqueryElem.
       whatever().
       on('a', 2)
```

[(repl)](https://decaffeinate-project.org/repl/#?useCS2=true&useJSModules=false&loose=false&evaluate=false&stage=full&code=class%20Whatever%0A%20%20%20no_problem%3A%20-%3E%0A%20%20%20%20%20%40jqueryElem.%0A%20%20%20%20%20%20%20whatever().%0A%20%20%20%20%20%20%20non_coffeescript_keyword('a'%2C%202)%0A%20%20%20explodes%3A%20-%3E%0A%20%20%20%20%20%40jqueryElem.%0A%20%20%20%20%20%20%20whatever().%0A%20%20%20%20%20%20%20on('a'%2C%202))

I get this error:

```
unexpected ')' at 180
```

The same thing happens with other keywords being used as method names:

* `on`
* `of`
* I got bored at this point, but you get the idea.....

To justify this goofy seeming request, this is what my actual code looked like:

```coffee

class Whatever
  someMethod: ->
    @scriptRewindButton = @scriptPlayerControls.append('button').
      attr('title','rewind to start').
      attr('disabled', 'disabled').
      on('click', @on_rewind_click)
    @scriptRewindButton.
      append('i').attr("class", "fa fa-fast-backward")

```

**Comment by eventualbuddha** [comment]
This is now fixed in v6.0.1. Your original source code now compiles to this:

```js
/*
 * decaffeinate suggestions:
 * DS102: Remove unnecessary code created because of implicit returns
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/master/docs/suggestions.md
 */
class Whatever {
   no_problem() {
     return this.jqueryElem.
       whatever().
       non_coffeescript_keyword('a', 2);
   }
   explodes() {
     return this.jqueryElem.
       whatever().
       on('a', 2);
   }
 }
```

You may need to clear your browser cache to see it correctly.

**Comment by smurp** [comment]
Thank you Brian!
